name: Build, Test, and Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore Hospital_Management_System/Hospital_Management_System.sln

      - name: Setup MSBuild path
        id: msbuild
        run: |
          $msbuildPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          echo "MSBUILD_PATH=$msbuildPath" >> $env:GITHUB_ENV

      - name: Build with MSBuild
        run: |
          & "$env:MSBUILD_PATH" 'Hospital_Management_System/Hospital_Management_System.sln' /p:Configuration=Release
        shell: pwsh

      - name: Run Tests
        run: |
          $testAssemblies = Get-ChildItem -Path "Hospital_Management_System/Hospital_Management_System/bin/Release" -Filter *.Tests.dll -Recurse
          $testAssemblies | ForEach-Object { & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" $_.FullName }
        shell: pwsh

      - name: Publish Artifacts
        run: |
          mkdir artifact
          cp -r Hospital_Management_System/Hospital_Management_System/bin/Release/* artifact/
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: artifact

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gescalante'
          slot-name: 'production'
          package: artifact
